
services:
  - type: web
    name: megapik-backend
    runtime: python
    plan: free
    # Python için varsayılan build (requirements.txt’i kurar)
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8001
    envVars:
      - key: GEMINI_API_KEY
        value: senin_api_keyin_buraya
      - key: HF_HOME       # Hugging Face model cache dizini
        value: /tmp/hf_home