
services:
  - type: web
    name: megapik-backend
    runtime: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: GEMINI_API_KEY
        value: senin_api_keyin_buraya
